
name: Hank Quinlan, Horrible Cop
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

plugins:
  - jekyll-sitemap
  - jekyll-feed

plugins: [jekyll-youtube]

twitter_username:     andrewjtech
github_username:      andrewjtech123
linkedin_username:    andrew-johnston-8b202511
google_plus_username: AleksandarTodorovićr3bl
facebook_username:    aleksandar.todorovic.r3bl
dribbble_username:
