
name: Andrew Johnston
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

plugins: [jekyll-youtube]

twitter_username:     andrewjtech
github_username:      andrewjtech123
linkedin_username:    andrew-johnston-8b202511
google_plus_username: AleksandarTodorovićr3bl
facebook_username:    aleksandar.todorovic.r3bl
dribbble_username:
